version: '3.8'

services:
  server:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  apache-static:
    build: ./apache-static
    ports:
      - "3000:80"
    
    

  db:
    image: postgres
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
